name: Java CI with Gradle

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # You can use 'temurin', 'zulu', etc.

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x MyProject/gradlew

      - name: Build with Gradle
        working-directory: MyProject
        run: ./gradlew build

      - name: Run tests
        working-directory: MyProject
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: MyProject/build/test-results/test/
